#!/usr/bin/env python
import json
import signal
from urllib.parse import urlencode
from urllib.request import build_opener

from gi.repository import Gtk, Gdk


def trans():
    tray = Gtk.StatusIcon()
    tray.set_from_stock(Gtk.STOCK_SELECT_FONT)
    tray.connect('activate', lambda w: fetch())
    tray.connect('popup-menu', lambda i, b, t: Gtk.main_quit())

    signal.signal(signal.SIGINT, lambda s, f: Gtk.main_quit())
    Gtk.main()


def call_google(text, to):
    url = 'http://translate.google.ru/translate_a/t'
    params = {
        'client': 'x',
        'sl': 'auto',
        'tl': to,
        'io': 'utf8',
        'oe': 'utf8',
        'text': text
    }

    opener = build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    f = opener.open('%s?%s' % (url, urlencode(params)))
    data = json.loads(f.read().decode())
    text = '\n'.join(r['trans'] for r in data['sentences'])
    return data['src'], text


def show(text):
    if not hasattr(show, 'win'):
        view = Gtk.TextView(left_margin=10, right_margin=10)
        view.set_wrap_mode(Gtk.WrapMode.WORD)
        view.set_justification(Gtk.Justification.FILL)
        view.connect('button-press-event', lambda w, e: win.hide())

        win = Gtk.Window(
            title='Tider', resizable=True, decorated=True,
            skip_pager_hint=True, skip_taskbar_hint=True,
            type=Gtk.WindowType.POPUP
        )
        win.set_keep_above(True)
        win.add(view)
        win.move(950, 30)
        win.set_trans = lambda text: view.get_buffer().set_text(text)

        show.win = win

    win = show.win
    win.set_trans(text)
    win.resize(400, 100)
    win.show_all()


def fetch():
    clip = Gtk.Clipboard.get(Gdk.SELECTION_PRIMARY)
    text = clip.wait_for_text()
    if not (text and text.strip()):
        return

    text = text.replace('\t', ' ').replace('\r', ' ')

    for lang in ['ru', 'en']:
        src_lang, result = call_google(text, to=lang)
        if src_lang != lang:
            show(result)
            return

if __name__ == '__main__':
    trans()
