#!/usr/bin/env python
import sys
import subprocess

from perevod import RELOAD

cmd = [sys.executable, '-m', 'perevod'] + sys.argv[1:]
try:
    code = subprocess.call(cmd)
    if code == RELOAD:
        subprocess.call(sys.argv)
except KeyboardInterrupt:
    raise SystemExit()
